# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions



name: Deploy on cloudera
description: Prototype to demonstrate semantic image search
author: iiithydclimatechangetrend
specification_version: 1.0
prototype_version: 2.0
date: "2022-03-25"

runtimes:
  - editor: Workbench
    kernel: Python 3.9
    edition: Standard

tasks:
  - type: run_session
    name: Install Dependencies
    script: scripts/install_dependencies.py
    kernel: python3
environment_variables:
  RANDOM_VARIABLE_NAME:
    default: "DEFAULT-VALUE"
    description: "A description providing user clarifying information about the variable."
    required: false

runtimes:
  - editor: Workbench ## Other acceptable values are determined by the runtimes available in your CML environment
    kernel: Python 3.10 ## Same here, check your runtimes (custom runtimes can be added as well)
    edition: Standard ## Particularly relevant if using GPUs, Nvidia GPU

## Below are some sample tasks based on some of the most popular aspects of AMP creation.
tasks:

  ## Install Dependencies Task
  - type: run_session
    name: Install Dependencies
    script: cml/install_dependencies.py
    short_summary: Install Requirements and Dependencies
    kernel: python3
    cpu: 2
    memory: 4

  ## Launch Streamlit App Task
  - type: start_application
    name: Streamlit App
    subdomain: streamlit
    script: scripts/launch_app.py
    short_summary: Start Streamlit application
    environment_variables:
      TASK_TYPE: START_APPLICATION
