name: Timberline Analysis
description: To find the ranges which are in critical condition and need immediate attention
author: Cloudera Inc.
specification_version: 1.0
prototype_version: 2.0
date: "2024-04-25"

runtimes:
  - editor: Workbench
    kernel: Python 3.9
    edition: Standard

tasks:
  - type: run_session
    name: Install Dependencies
    script: scripts/install_dependencies.py
    kernel: python3
    cpu: 2
    memory: 4

  - type: start_application
    name: Application to serve UI
    short_summary: Create an application to serve the image analysis UI
    subdomain: imageanalysis
    script: scripts/launch_app.py
    environment_variables:
      TASK_TYPE: START_APPLICATION